version: '3.4'

networks:

  backend:
    driver: bridge

services:

  provaml_database:
    container_name: provaml_database
    image: ${REGISTRY:-provaml}/database:${PLATFORM:-linux}-${TAG:-latest}
    mem_limit: 2G
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "5434:1433"
    networks:
      - backend

  provaml_migration:
    container_name: provaml_migration
    image: ${REGISTRY:-provaml}/migration:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./ProvaML.Migration
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Server=provaml_database,1433;Database=ProvaML;User Id=sa;Password=Dev123456789;
    depends_on:
      - provaml_database
    networks:
      - backend 

  provaml_api:
    image: ${REGISTRY:-provaml}/api:${PLATFORM:-linux}-${TAG:-latest}
    container_name: "provaml_api"
    build:
      context: .
      dockerfile: ./ProvaML.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=provaml_database,1433;Database=ProvaML;User Id=sa;Password=Dev123456789;
    ports:
      - "8081:80"
    depends_on:
      - provaml_database
      - provaml_migration
    networks: 
      - backend 

  provaml_app:
    image: ${REGISTRY:-provaml}/app:${PLATFORM:-linux}-${TAG:-latest}
    container_name: "provaml_app"
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - provaml_api
    networks: 
      - backend 